from datetime import date, datetime, timedelta, timezone

from fastapi import HTTPException
from sqlalchemy import and_, func, literal_column, or_, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from src.orders.date_range import order_tz
from src.config import settings
from src.models.account import Account
from src.models.affiliate import (
    AffiliateAccountOverride, AffiliateClick, AffiliateCommission, AffiliateFund, AffiliateFundEntry,
)
from src.models.category import Category
from src.models.order import Order, OrderStatus
from src.models.product import Product, ProductVariant
from src.models.promotion import Promotion, PromotionRedemption
from src.models.wallet import Wallet, WithdrawRequest, WithdrawStatus
from src.fees.service import order_fee_percent
from src.wallet.service import clawback_affiliate_commission, credit_affiliate_commission, escrow_settlement

from .attribution import CLICK_DEDUP_WINDOW, same_public_ip
from .settings import EARNING_DAYS_RANGE, COMMISSION_PERCENT_RANGE, get_affiliate_settings


_PAID_COMMISSION = AffiliateCommission.clawed_back_at.is_(None)
# Orders whose money is still held: commission comes when they settle.
PENDING_COMMISSION_STATUSES = (
    OrderStatus.pending, OrderStatus.processing, OrderStatus.delivered, OrderStatus.disputed,
)
# Orders that count as "generated by the referral" on the dashboard.
_REFERRED_ORDER_EXCLUDED = (OrderStatus.cancelled, OrderStatus.refunded)


async def _lock_fund(db: AsyncSession) -> AffiliateFund:
    fund = await db.get(AffiliateFund, 1, with_for_update=True)
    if fund is None:
        fund = AffiliateFund(id=1, balance=0)
        db.add(fund)
        await db.flush()
        fund = await db.get(AffiliateFund, 1, with_for_update=True)
        assert fund is not None
    return fund


async def record_click(
    code: str,
    db: AsyncSession,
    path: str | None = None,
    referrer: str | None = None,
    visitor_id: str | None = None,
    ip: str | None = None,
) -> None:
    """Record a referral-link click, deduplicated per visitor per 24h.

    Identity is the client-persisted visitor_id when present, else the client
    IP — refreshes and repeat visits inside the window don't add clicks.
    A request with neither identity is dropped rather than counted, since it
    could be replayed indefinitely.
    """
    affiliate = await db.scalar(select(Account).where(Account.affiliate_code == code))
    if not affiliate:
        return

    # Prefer visitor_id when present; only fall back to IP for anonymous
    # clients. Combining both with OR would collapse distinct visitors
    # sharing a NAT/IP (or the single test client IP) into one click.
    if visitor_id:
        identity_filter = AffiliateClick.visitor_id == visitor_id
    elif ip:
        identity_filter = AffiliateClick.ip == ip
    else:
        return

    # Serialise check-then-insert per visitor: two beacons in flight (double
    # mount, retry) must still count one click.
    await db.execute(
        text("SELECT pg_advisory_xact_lock(hashtext(:k))"),
        {"k": f"affiliate_click:{affiliate.id}:{visitor_id or ip}"},
    )
    window_start = datetime.now(timezone.utc) - CLICK_DEDUP_WINDOW
    duplicate = await db.scalar(
        select(AffiliateClick.id).where(
            AffiliateClick.affiliate_account_id == affiliate.id,
            AffiliateClick.created_at >= window_start,
            identity_filter,
        ).limit(1)
    )
    if duplicate:
        return

    db.add(
        AffiliateClick(
            affiliate_account_id=affiliate.id,
            path=path,
            referrer=referrer,
            visitor_id=visitor_id,
            ip=ip,
        )
    )
    await db.commit()


def resolve_rate(
    product_rate: float | None,
    category_rate: float | None,
    account_rate: float | None,
    default_rate: float,
) -> float | None:
    """Commission % of the platform fee for one order, or None when it earns
    nothing. Precedence:

    1. a product or category explicitly set to 0 blocks commission for
       everyone — it is the admin's "no referral payout on this item";
    2. the referrer's own rate (``affiliate_account_overrides``, a KOL deal);
    3. the product's rate, else its category's rate;
    4. the programme default (``affiliate_runtime_config``).
    """
    explicit = product_rate if product_rate is not None else category_rate
    if explicit is not None and explicit <= 0:
        return None
    if account_rate is not None:
        rate = account_rate
    elif explicit is not None:
        rate = explicit
    else:
        rate = default_rate
    if rate <= 0 or rate > 100:
        return None
    return float(rate)


async def get_override(account_id: int, db: AsyncSession) -> AffiliateAccountOverride | None:
    return await db.get(AffiliateAccountOverride, account_id)


def effective_earning_days(config: dict, override: AffiliateAccountOverride | None) -> int:
    if override is not None and override.earning_days is not None:
        return int(override.earning_days)
    return int(config["earning_days"])


async def _order_product(order: Order, db: AsyncSession) -> Product | None:
    if order.product_id:
        return await db.get(Product, order.product_id)
    if order.variant_id:
        variant = await db.get(ProductVariant, order.variant_id)
        if variant:
            return await db.get(Product, variant.product_id)
    return None


async def _commission_quote(
    order: Order, buyer: Account, affiliate: Account, config: dict, db: AsyncSession,
    *, via_code: bool = False,
) -> tuple[float, int, int] | None:
    """(rate %, fee base, amount) the referrer earns on this order once it
    settles, or None when it earns nothing. Deterministic rules only; the
    daily cap and the fund balance are checked at payout time.

    ``via_code``: the order used the referrer's own promo code, which is an
    explicit attribution of this order, so the earning window does not apply.
    """
    if (
        not affiliate.is_active
        or affiliate.id == order.buyer_id
        or affiliate.id == order.seller_id
    ):
        return None
    override = await get_override(affiliate.id, db)
    earning_days = effective_earning_days(config, override)
    if not via_code and earning_days > 0:
        start = buyer.referred_at or buyer.created_at
        if start is not None:
            cutoff = start + timedelta(days=earning_days)
            if (order.created_at or datetime.now(timezone.utc)) > cutoff:
                return None

    product = await _order_product(order, db)
    product_rate = category_rate = None
    if product:
        product_rate = product.commission_rate
        if product_rate is None:
            category = await db.get(Category, product.category_id)
            category_rate = category.commission_rate if category else None
    rate = resolve_rate(
        product_rate, category_rate,
        override.commission_percent_of_fee if override is not None else None,
        float(config["commission_percent_of_fee"]),
    )
    if rate is None:
        return None

    seller = await db.get(Account, order.seller_id)
    fee_percent = await order_fee_percent(order, seller.seller_tier if seller else "new", db)
    _remaining, fee_base = escrow_settlement(order.total_amount, order.refunded_amount, fee_percent)
    amount = round(fee_base * rate / 100)
    if amount <= 0:
        return None

    if same_public_ip(affiliate, buyer):
        return None
    return rate, fee_base, amount


async def order_referrer(order: Order, buyer: Account, db: AsyncSession) -> tuple[int | None, bool]:
    """(referrer id, via_code) owed this order's commission: the KOL whose
    promo code the order used (snapshot on the redemption), else the buyer's
    referrer."""
    code_affiliate = await db.scalar(
        select(PromotionRedemption.affiliate_account_id).where(PromotionRedemption.order_id == order.id)
    )
    if code_affiliate is not None:
        return int(code_affiliate), True
    return buyer.referred_by_id, False


def _owned_by(affiliate_id: int):
    """Orders (joined with their buyer and outer-joined with their promo
    redemption) whose commission belongs to ``affiliate_id``."""
    return or_(
        PromotionRedemption.affiliate_account_id == affiliate_id,
        and_(PromotionRedemption.affiliate_account_id.is_(None), Account.referred_by_id == affiliate_id),
    )


async def apply_affiliate_commission(order: Order, db: AsyncSession) -> None:
    """Pay the referrer their share of the *platform fee* on a settled order.

    Called inside the settlement transaction (escrow release / buyer confirm
    / dispute settlement); idempotent per order. The referrer is the KOL of a
    promo code the order used, else the buyer's referrer. The rate follows
    ``resolve_rate``; either way it is applied to the fee the marketplace
    actually earned, never to the order total, so a 0 % fee order pays
    nothing. Commission is credited to the referrer's main wallet.
    """
    config = await get_affiliate_settings(db)
    if not config["enabled"]:
        return
    buyer = await db.get(Account, order.buyer_id)
    if not buyer:
        return
    affiliate_id, via_code = await order_referrer(order, buyer, db)
    if affiliate_id is None:
        return
    affiliate = await db.get(Account, affiliate_id)
    if not affiliate:
        return

    existing = await db.scalar(
        select(AffiliateCommission.id).where(AffiliateCommission.order_id == order.id)
    )
    if existing:
        return

    quote = await _commission_quote(order, buyer, affiliate, config, db, via_code=via_code)
    if quote is None:
        return
    rate, fee_base, amount = quote

    # Fund lock first: it serialises settlements, so the per-day count below
    # cannot be passed by two concurrent orders of the same affiliate.
    fund = await _lock_fund(db)
    day_start = datetime.now(timezone.utc) - timedelta(hours=24)
    recent = int(
        await db.scalar(
            select(func.count(AffiliateCommission.id)).where(
                AffiliateCommission.affiliate_account_id == affiliate.id,
                AffiliateCommission.created_at >= day_start,
                _PAID_COMMISSION,
            )
        )
        or 0
    )
    if recent >= int(config["max_commissions_per_day"]):
        return

    if fund.balance < amount:
        return

    db.add(
        AffiliateCommission(
            order_id=order.id,
            affiliate_account_id=affiliate.id,
            buyer_account_id=buyer.id,
            rate_percent=rate,
            fee_base_amount=fee_base,
            amount=amount,
        )
    )
    fund.balance -= amount
    db.add(
        AffiliateFundEntry(
            amount=-amount,
            kind="commission",
            reference_id=str(order.id),
        )
    )
    await credit_affiliate_commission(affiliate.id, amount, order.id, db)


async def pending_commission(affiliate: Account, db: AsyncSession) -> tuple[int, int]:
    """(expected amount, order count) of commission not yet paid: real orders
    owed to this referrer (referred buyers, or the referrer's promo codes)
    whose money is still held. It is an estimate — the order may still be
    refunded, and the daily cap and fund balance apply at payout — and it is
    not a wallet balance; nothing is reserved."""
    config = await get_affiliate_settings(db)
    if not config["enabled"]:
        return 0, 0
    paid = select(AffiliateCommission.id).where(AffiliateCommission.order_id == Order.id).exists()
    rows = (await db.execute(
        select(Order, Account, PromotionRedemption.affiliate_account_id)
        .join(Account, Account.id == Order.buyer_id)
        .outerjoin(PromotionRedemption, PromotionRedemption.order_id == Order.id)
        .where(
            _owned_by(affiliate.id),
            Order.status.in_(PENDING_COMMISSION_STATUSES),
            Order.is_seeded.is_(False),
            ~paid,
        )
    )).all()
    total = count = 0
    for order, buyer, code_affiliate in rows:
        quote = await _commission_quote(
            order, buyer, affiliate, config, db, via_code=code_affiliate is not None,
        )
        if quote is not None:
            total += quote[2]
            count += 1
    return total, count


async def clawback_commission_for_order(order: Order, db: AsyncSession) -> None:
    """Reverse a paid commission when the order is fully refunded. Idempotent."""
    commission = await db.scalar(
        select(AffiliateCommission)
        .where(AffiliateCommission.order_id == order.id)
        .with_for_update()
    )
    if commission is None or commission.clawed_back_at is not None:
        return

    fund = await _lock_fund(db)
    recovered = await clawback_affiliate_commission(
        commission.affiliate_account_id, commission.amount, order.id, db
    )
    # Only what the wallet gave back returns to the budget: commission the
    # affiliate already spent or locked in a withdrawal has left the platform.
    fund.balance += recovered
    db.add(
        AffiliateFundEntry(
            amount=recovered,
            kind="clawback",
            reference_id=str(order.id),
            note=None if recovered == commission.amount else f"commission={commission.amount} wallet_recovered={recovered}",
        )
    )
    commission.clawed_back_at = datetime.now(timezone.utc)


async def earned_commission(account_id: int, db: AsyncSession) -> int:
    """Commission credited to the account and not clawed back, all time."""
    return int(await db.scalar(
        select(func.coalesce(func.sum(AffiliateCommission.amount), 0)).where(
            AffiliateCommission.affiliate_account_id == account_id, _PAID_COMMISSION,
        )
    ) or 0)


async def withdrawable_commission(account_id: int, db: AsyncSession, *, earned: int | None = None) -> int:
    """What an account that is not a seller (a KOL / referrer) may withdraw to
    a bank right now: commission earned and not clawed back, less every
    withdrawal it already asked for (pending, approved or paid — only a
    rejected one gives its share back), and never more than the wallet's
    available balance. Deposits, cashback and other credits are spendable
    on the marketplace but never withdrawable this way, so money cannot be
    deposited and taken straight back out. Sellers withdraw under their own
    rules (``wallet.request_withdraw``)."""
    if earned is None:
        earned = await earned_commission(account_id, db)
    requested = int(await db.scalar(
        select(func.coalesce(func.sum(WithdrawRequest.amount), 0)).where(
            WithdrawRequest.account_id == account_id, WithdrawRequest.status != WithdrawStatus.rejected,
        )
    ) or 0)
    available = int(await db.scalar(
        select(Wallet.available_balance).where(Wallet.account_id == account_id)
    ) or 0)
    return max(0, min(earned - requested, available))


async def get_fund_balance(db: AsyncSession) -> int:
    fund = await db.get(AffiliateFund, 1)
    if fund is not None:
        return int(fund.balance)
    return int(await db.scalar(select(func.coalesce(func.sum(AffiliateFundEntry.amount), 0))) or 0)


async def get_fund_overview(db: AsyncSession, limit: int = 30) -> dict:
    balance = await get_fund_balance(db)
    spent = int(
        await db.scalar(
            select(func.coalesce(func.sum(AffiliateFundEntry.amount), 0)).where(
                AffiliateFundEntry.kind == "commission"
            )
        )
        or 0
    )
    clawed = int(
        await db.scalar(
            select(func.coalesce(func.sum(AffiliateFundEntry.amount), 0)).where(
                AffiliateFundEntry.kind == "clawback"
            )
        )
        or 0
    )
    topped = int(
        await db.scalar(
            select(func.coalesce(func.sum(AffiliateFundEntry.amount), 0)).where(
                AffiliateFundEntry.kind == "topup"
            )
        )
        or 0
    )
    rows = await db.execute(
        select(AffiliateFundEntry).order_by(AffiliateFundEntry.created_at.desc()).limit(limit)
    )
    entries = [
        {
            "id": e.id,
            "amount": e.amount,
            "kind": e.kind,
            "reference_id": e.reference_id,
            "note": e.note,
            "created_at": e.created_at,
        }
        for e in rows.scalars().all()
    ]
    # spent is stored negative; clawbacks restore budget so net paid out shrinks.
    return {
        "balance": balance,
        "total_topped_up": topped,
        "total_paid_out": -spent - clawed,
        "entries": entries,
    }


async def topup_fund(amount: int, admin_id: int, db: AsyncSession, note: str | None = None) -> dict:
    from src.audit.service import log_event
    from src.logging import current_request_id

    if amount <= 0:
        raise HTTPException(status_code=400, detail="Số tiền phải lớn hơn 0")
    fund = await _lock_fund(db)
    fund.balance += amount
    db.add(
        AffiliateFundEntry(amount=amount, kind="topup", note=note, created_by=admin_id)
    )
    await log_event(
        db, "info", f"Affiliate fund topped up by {amount}",
        request_id=current_request_id(),
        metadata={
            "event": "affiliate_fund_topup",
            "actor_id": admin_id,
            "actor_type": "admin",
            "subject_type": "affiliate_fund",
            "subject_id": admin_id,
            "outcome": "success",
            "source": "admin",
            "amount": amount,
        },
    )
    await db.commit()
    return await get_fund_overview(db)


async def update_affiliate_code(account_id: int, new_code: str, db: AsyncSession) -> Account:
    """Admin-set an affiliate's referral code.

    referred_by_id and affiliate_clicks link by account id, so existing
    attributions and click history are unaffected; only external links that
    still carry the old code stop resolving.
    """
    code = new_code.strip().upper()
    if not (4 <= len(code) <= 8) or not code.isalnum():
        raise HTTPException(status_code=422, detail="Mã phải dài 4–8 ký tự chữ/số")
    account = await db.get(Account, account_id)
    if not account:
        raise HTTPException(status_code=404, detail="Không tìm thấy tài khoản")
    clash = await db.scalar(
        select(Account.id).where(Account.affiliate_code == code, Account.id != account_id)
    )
    if clash:
        raise HTTPException(status_code=409, detail="Mã này đã được dùng")
    account.affiliate_code = code
    await db.commit()
    await db.refresh(account)
    return account


def _terms_view(account_id: int, override: AffiliateAccountOverride | None, config: dict) -> dict:
    percent = override.commission_percent_of_fee if override is not None else None
    days = override.earning_days if override is not None else None
    return {
        "account_id": account_id,
        "commission_percent_of_fee": percent,
        "earning_days": days,
        "note": override.note if override is not None else None,
        "updated_at": override.updated_at if override is not None else None,
        "updated_by_id": override.updated_by_id if override is not None else None,
        "default_commission_percent_of_fee": float(config["commission_percent_of_fee"]),
        "default_earning_days": int(config["earning_days"]),
        "effective_commission_percent_of_fee": float(percent if percent is not None else config["commission_percent_of_fee"]),
        "effective_earning_days": effective_earning_days(config, override),
    }


async def _terms_account(account_id: int, db: AsyncSession) -> Account:
    account = await db.get(Account, account_id)
    if account is None or account.is_seeded:
        raise HTTPException(status_code=404, detail="Không tìm thấy tài khoản")
    return account


async def get_account_terms(account_id: int, db: AsyncSession) -> dict:
    await _terms_account(account_id, db)
    return _terms_view(account_id, await get_override(account_id, db), await get_affiliate_settings(db))


async def set_account_terms(
    account_id: int,
    db: AsyncSession,
    *,
    actor_id: int,
    commission_percent_of_fee: float | None,
    earning_days: int | None,
    note: str | None = None,
) -> dict:
    """Admin sets (or clears, with both values None) one referrer's own
    commission % of the platform fee and earning window (0 = lifetime).
    Applies to commissions computed from now on — settled ones keep theirs.
    Every real change is an ``affiliate_account_terms_changed`` audit row."""
    from src.audit.service import log_event
    from src.logging import current_request_id

    if commission_percent_of_fee is not None:
        low, high = COMMISSION_PERCENT_RANGE
        if not (low <= commission_percent_of_fee <= high):
            raise HTTPException(status_code=422, detail="Hoa hồng phải từ 0 đến 100%")
    if earning_days is not None:
        low, high = EARNING_DAYS_RANGE
        if not (low <= earning_days <= high):
            raise HTTPException(status_code=422, detail="Số ngày hưởng phải từ 0 (trọn đời) đến 3650")
    note = (note or "").strip() or None

    await _terms_account(account_id, db)
    override = await db.get(AffiliateAccountOverride, account_id, with_for_update=True)
    old = {
        "commission_percent_of_fee": override.commission_percent_of_fee if override else None,
        "earning_days": override.earning_days if override else None,
    }
    new = {"commission_percent_of_fee": commission_percent_of_fee, "earning_days": earning_days}
    old_note = override.note if override else None

    if commission_percent_of_fee is None and earning_days is None:
        if override is not None:
            await db.delete(override)
        override = None
    else:
        if override is None:
            override = AffiliateAccountOverride(account_id=account_id)
            db.add(override)
        override.commission_percent_of_fee = commission_percent_of_fee
        override.earning_days = earning_days
        override.note = note
        override.updated_by_id = actor_id

    if old != new or (override is not None and old_note != note):
        await log_event(
            db, "info", f"Affiliate terms of account {account_id} updated",
            request_id=current_request_id(),
            metadata={
                "event": "affiliate_account_terms_changed",
                "actor_id": actor_id,
                "actor_type": "admin",
                "subject_type": "account",
                "subject_id": account_id,
                "old": old,
                "new": new,
                "outcome": "success",
                "source": "admin",
            },
        )
    await db.commit()
    if override is not None:
        await db.refresh(override)
    return _terms_view(account_id, override, await get_affiliate_settings(db))


AFFILIATE_SORTS = ("commission", "clicks", "signups", "orders", "newest", "email")


async def list_affiliates_admin(
    db: AsyncSession,
    search: str | None = None,
    page: int = 1,
    per_page: int = 20,
    sort: str = "commission",
    active_only: bool = False,
    custom_only: bool = False,
) -> dict:
    """Paginated list of accounts with aggregated affiliate stats.

    Uses subqueries per aggregate to avoid cartesian-product sum inflation.
    ``active_only`` keeps accounts with at least one click, sign-up or paid
    commission; ``custom_only`` keeps accounts with their own terms or a KOL
    promo code; ``summary`` is over the whole (searched) set, not the page.
    """
    clicks_subq = (
        select(
            AffiliateClick.affiliate_account_id.label("aid"),
            func.count(AffiliateClick.id).label("clicks"),
        )
        .group_by(AffiliateClick.affiliate_account_id)
        .subquery()
    )
    signups_subq = (
        select(
            Account.referred_by_id.label("rid"),
            func.count(Account.id).label("signups"),
        )
        .where(Account.referred_by_id.isnot(None), Account.referred_via_promotion_id.is_(None))
        .group_by(Account.referred_by_id)
        .subquery()
    )
    comm_subq = (
        select(
            AffiliateCommission.affiliate_account_id.label("aid"),
            func.count(AffiliateCommission.id).label("orders"),
            func.coalesce(func.sum(AffiliateCommission.amount), 0).label("commission"),
        )
        .where(_PAID_COMMISSION)
        .group_by(AffiliateCommission.affiliate_account_id)
        .subquery()
    )

    codes_subq = (
        select(
            Promotion.affiliate_account_id.label("aid"),
            func.count(Promotion.id).label("codes"),
        )
        .where(Promotion.affiliate_account_id.isnot(None))
        .group_by(Promotion.affiliate_account_id)
        .subquery()
    )

    query = (
        select(
            Account.id,
            Account.email,
            Account.affiliate_code,
            func.coalesce(clicks_subq.c.clicks, 0).label("clicks"),
            func.coalesce(signups_subq.c.signups, 0).label("signups"),
            func.coalesce(comm_subq.c.orders, 0).label("orders"),
            func.coalesce(comm_subq.c.commission, 0).label("commission"),
            AffiliateAccountOverride.commission_percent_of_fee.label("custom_percent"),
            AffiliateAccountOverride.earning_days.label("custom_earning_days"),
            func.coalesce(codes_subq.c.codes, 0).label("promo_codes"),
        )
        .outerjoin(clicks_subq, clicks_subq.c.aid == Account.id)
        .outerjoin(signups_subq, signups_subq.c.rid == Account.id)
        .outerjoin(comm_subq, comm_subq.c.aid == Account.id)
        .outerjoin(AffiliateAccountOverride, AffiliateAccountOverride.account_id == Account.id)
        .outerjoin(codes_subq, codes_subq.c.aid == Account.id)
    )
    if search:
        query = query.where(Account.email.ilike(f"%{search}%"))
    if active_only:
        query = query.where(
            or_(clicks_subq.c.clicks > 0, signups_subq.c.signups > 0, comm_subq.c.orders > 0)
        )
    if custom_only:
        query = query.where(or_(AffiliateAccountOverride.account_id.isnot(None), codes_subq.c.codes > 0))

    base = query.subquery()
    summary_row = (await db.execute(
        select(
            func.count(base.c.id),
            func.count(base.c.id).filter(or_(base.c.clicks > 0, base.c.signups > 0, base.c.orders > 0)),
            func.coalesce(func.sum(base.c.clicks), 0),
            func.coalesce(func.sum(base.c.signups), 0),
            func.coalesce(func.sum(base.c.orders), 0),
            func.coalesce(func.sum(base.c.commission), 0),
        )
    )).one()
    total = int(summary_row[0] or 0)
    summary = {
        "accounts": total,
        "active": int(summary_row[1] or 0),
        "clicks": int(summary_row[2] or 0),
        "signups": int(summary_row[3] or 0),
        "orders": int(summary_row[4] or 0),
        "commission": int(summary_row[5] or 0),
    }

    order_by = {
        "commission": (base.c.commission.desc(), base.c.orders.desc(), base.c.clicks.desc(), base.c.id.asc()),
        "clicks": (base.c.clicks.desc(), base.c.id.asc()),
        "signups": (base.c.signups.desc(), base.c.id.asc()),
        "orders": (base.c.orders.desc(), base.c.id.asc()),
        "newest": (base.c.id.desc(),),
        "email": (base.c.email.asc(),),
    }.get(sort) or (base.c.commission.desc(), base.c.id.asc())

    rows = await db.execute(
        select(base).order_by(*order_by).offset((page - 1) * per_page).limit(per_page)
    )
    items = [
        {
            "id": r.id,
            "email": r.email,
            "affiliate_code": r.affiliate_code,
            "clicks": int(r.clicks or 0),
            "signups": int(r.signups or 0),
            "orders": int(r.orders or 0),
            "commission": int(r.commission or 0),
            "custom_percent": r.custom_percent,
            "custom_earning_days": r.custom_earning_days,
            "promo_codes": int(r.promo_codes or 0),
        }
        for r in rows.all()
    ]
    return {"items": items, "total": total, "page": page, "per_page": per_page, "summary": summary}


def _parse_range(date_from: str | None, date_to: str | None, tz: str | None = None) -> tuple[datetime | None, datetime | None]:
    """Whole calendar days in the viewer's zone (default Asia/Ho_Chi_Minh)."""
    zone = order_tz(tz)
    try:
        start_date = date.fromisoformat(date_from) if date_from else None
        end_date = date.fromisoformat(date_to) if date_to else None
    except ValueError:
        raise HTTPException(
            status_code=422,
            detail="date_from/date_to phải theo định dạng YYYY-MM-DD",
        )

    effective_end = end_date or (datetime.now(zone).date() if start_date else None)
    if start_date and effective_end:
        if start_date > effective_end:
            raise HTTPException(status_code=422, detail="date_from không được sau date_to")
        if (effective_end - start_date).days + 1 > 366:
            raise HTTPException(status_code=422, detail="Khoảng ngày không được vượt quá 366 ngày")

    start = datetime.combine(start_date, datetime.min.time(), tzinfo=zone) if start_date else None
    end = (
        datetime.combine(end_date + timedelta(days=1), datetime.min.time(), tzinfo=zone)
        if end_date
        else None
    )
    return start, end


async def get_affiliate_stats(
    account_id: int,
    db: AsyncSession,
    date_from: str | None = None,
    date_to: str | None = None,
    reveal_spend: bool = False,
    tz: str | None = None,
) -> dict:
    start, end = _parse_range(date_from, date_to, tz)

    account = await db.get(Account, account_id)
    code = account.affiliate_code if account else ""
    link = f"{settings.frontend_base_url}/?ref={code}"

    clicks_q = select(func.count(AffiliateClick.id)).where(
        AffiliateClick.affiliate_account_id == account_id
    )
    # Sign-ups through the link; buyers attached by a KOL code are counted on
    # their code instead (``promo_codes``).
    signups_q = select(func.count(Account.id)).where(
        Account.referred_by_id == account_id, Account.referred_via_promotion_id.is_(None),
    )
    referred_orders_q = (
        select(func.count(Order.id))
        .join(Account, Account.id == Order.buyer_id)
        .outerjoin(PromotionRedemption, PromotionRedemption.order_id == Order.id)
        .where(
            _owned_by(account_id),
            Order.buyer_id != account_id,
            Order.is_seeded.is_(False),
            Order.status.notin_(_REFERRED_ORDER_EXCLUDED),
        )
    )
    commission_q = select(
        func.count(AffiliateCommission.id),
        func.coalesce(func.sum(AffiliateCommission.amount), 0),
    ).where(
        AffiliateCommission.affiliate_account_id == account_id,
        _PAID_COMMISSION,
    )
    revenue_q = (
        select(func.coalesce(func.sum(Order.total_amount), 0))
        .join(AffiliateCommission, AffiliateCommission.order_id == Order.id)
        .where(
            AffiliateCommission.affiliate_account_id == account_id,
            _PAID_COMMISSION,
        )
    )

    if start:
        clicks_q = clicks_q.where(AffiliateClick.created_at >= start)
        signups_q = signups_q.where(Account.created_at >= start)
        referred_orders_q = referred_orders_q.where(Order.created_at >= start)
        commission_q = commission_q.where(AffiliateCommission.created_at >= start)
        revenue_q = revenue_q.where(AffiliateCommission.created_at >= start)
    if end:
        clicks_q = clicks_q.where(AffiliateClick.created_at < end)
        signups_q = signups_q.where(Account.created_at < end)
        referred_orders_q = referred_orders_q.where(Order.created_at < end)
        commission_q = commission_q.where(AffiliateCommission.created_at < end)
        revenue_q = revenue_q.where(AffiliateCommission.created_at < end)

    clicks = await db.scalar(clicks_q) or 0
    signups = await db.scalar(signups_q) or 0
    commission_row = (await db.execute(commission_q)).one()
    orders_count = int(commission_row[0] or 0)
    commission_total = int(commission_row[1] or 0)
    revenue = int(await db.scalar(revenue_q) or 0)

    referred_orders = int(await db.scalar(referred_orders_q) or 0)

    pending_amount, pending_orders = (
        await pending_commission(account, db) if account else (0, 0)
    )
    # Commission is credited straight into the main wallet; what is still
    # "available" is everything credited and not clawed back (all time).
    available = await earned_commission(account_id, db)
    wallet_available = int(await db.scalar(
        select(Wallet.available_balance).where(Wallet.account_id == account_id)
    ) or 0)
    totals = {
        "clicks": int(clicks),
        "signups": int(signups),
        "orders": orders_count,
        "referred_orders": referred_orders,
        "revenue": revenue,
        "commission": commission_total,
        "pending_commission": pending_amount,
        "pending_orders": pending_orders,
        "available_commission": available,
        "wallet_available": wallet_available,
        "withdrawable_commission": await withdrawable_commission(account_id, db, earned=available),
    }
    override = await get_override(account_id, db)
    custom_terms = (
        {
            "commission_percent_of_fee": override.commission_percent_of_fee,
            "earning_days": override.earning_days,
        }
        if override is not None
        and (override.commission_percent_of_fee is not None or override.earning_days is not None)
        else None
    )

    timeseries = await _build_timeseries(account_id, db, start, end, date_from, date_to, tz)

    referred_users = await _get_referred_users(account_id, db, start, end, reveal_spend=reveal_spend)

    recent = await db.execute(
        select(AffiliateCommission)
        .where(
            AffiliateCommission.affiliate_account_id == account_id,
            _PAID_COMMISSION,
        )
        .order_by(AffiliateCommission.created_at.desc())
        .limit(20)
    )
    commissions: list[dict] = []
    for c in recent.scalars().all():
        order = await db.get(Order, c.order_id)
        product_title = None
        if order and order.product_id:
            product = await db.get(Product, order.product_id)
            product_title = product.title if product else None
        elif order and order.variant_id:
            variant = await db.get(ProductVariant, order.variant_id)
            if variant:
                product = await db.get(Product, variant.product_id)
                product_title = product.title if product else None
        commissions.append({
            "id": c.id,
            "order_id": c.order_id,
            "order_code": order.order_code if order else None,
            "buyer_account_id": c.buyer_account_id,
            "rate_percent": c.rate_percent,
            "fee_base_amount": c.fee_base_amount,
            "amount": c.amount,
            "created_at": c.created_at,
            "product_title": product_title,
            "order_total": order.total_amount if order else None,
        })

    return {
        "code": code,
        "link": link,
        "email": account.email if account else None,
        "totals": totals,
        "timeseries": timeseries,
        "commissions": commissions,
        "referred_users": referred_users,
        "custom_terms": custom_terms,
        # Sellers withdraw their balance; anyone else only earned commission.
        "can_withdraw": account is not None,
        "withdraw_source": (
            "seller_balance" if account is not None and "seller" in (account.roles or []) else "affiliate_commission"
        ),
        "promo_codes": await affiliate_promo_codes(account_id, db),
    }


async def affiliate_promo_codes(account_id: int, db: AsyncSession) -> list[dict]:
    """The KOL's own promo campaigns with what each one brought in: orders
    (redemptions whose order was not cancelled), buyers attached to the KOL
    by the code, and commission paid on those orders (not clawed back)."""
    promos = list((await db.execute(
        select(Promotion)
        .where(Promotion.affiliate_account_id == account_id)
        .order_by(Promotion.created_at.desc())
    )).scalars())
    ids = [p.id for p in promos]
    if not ids:
        return []
    uses = dict((await db.execute(
        select(PromotionRedemption.promotion_id, func.count(PromotionRedemption.id))
        .join(Order, Order.id == PromotionRedemption.order_id)
        .where(
            PromotionRedemption.promotion_id.in_(ids),
            PromotionRedemption.affiliate_account_id == account_id,
            Order.status != OrderStatus.cancelled,
        )
        .group_by(PromotionRedemption.promotion_id)
    )).all())
    buyers = dict((await db.execute(
        select(Account.referred_via_promotion_id, func.count(Account.id))
        .where(Account.referred_via_promotion_id.in_(ids), Account.referred_by_id == account_id)
        .group_by(Account.referred_via_promotion_id)
    )).all())
    earned = dict((await db.execute(
        select(PromotionRedemption.promotion_id, func.coalesce(func.sum(AffiliateCommission.amount), 0))
        .join(AffiliateCommission, AffiliateCommission.order_id == PromotionRedemption.order_id)
        .where(
            PromotionRedemption.promotion_id.in_(ids),
            AffiliateCommission.affiliate_account_id == account_id,
            _PAID_COMMISSION,
        )
        .group_by(PromotionRedemption.promotion_id)
    )).all())
    now = datetime.now(timezone.utc)
    return [
        {
            "code": p.code,
            "name": p.name,
            "discount_type": p.discount_type.value,
            "discount_value": p.discount_value,
            "max_discount_amount": p.max_discount_amount,
            "ends_at": p.ends_at,
            "active": bool(
                p.is_active and p.archived_at is None
                and (p.starts_at is None or p.starts_at <= now)
                and (p.ends_at is None or p.ends_at > now)
            ),
            "orders": int(uses.get(p.id, 0)),
            "buyers": int(buyers.get(p.id, 0)),
            "commission": int(earned.get(p.id, 0)),
        }
        for p in promos
    ]


async def _get_referred_users(
    account_id: int,
    db: AsyncSession,
    start: datetime | None,
    end: datetime | None,
    reveal_spend: bool = False,
) -> list[dict]:
    """Accounts attributed to this affiliate (ref-link sign-ups and buyers a
    KOL code attached), most recent attribution first.

    total_spent is only populated when reveal_spend=True (admin view) — the
    self-service affiliate page must not leak other users' spending.
    """
    orders_subq = (
        select(
            Order.buyer_id.label("bid"),
            func.count(Order.id).label("order_count"),
            func.coalesce(func.sum(Order.total_amount), 0).label("total_spent"),
        )
        # Seeded demo orders spent no money and belong to accounts that cannot
        # be referred, so they must not appear as referral spend.
        .where(Order.is_seeded.is_(False))
        .group_by(Order.buyer_id)
        .subquery()
    )
    attributed_at = func.coalesce(Account.referred_at, Account.created_at)
    query = (
        select(
            Account.id,
            Account.email,
            Account.created_at,
            Promotion.code.label("via_code"),
            func.coalesce(orders_subq.c.order_count, 0).label("order_count"),
            func.coalesce(orders_subq.c.total_spent, 0).label("total_spent"),
        )
        .outerjoin(orders_subq, orders_subq.c.bid == Account.id)
        .outerjoin(Promotion, Promotion.id == Account.referred_via_promotion_id)
        .where(Account.referred_by_id == account_id)
        .order_by(attributed_at.desc())
        .limit(100)
    )
    if start:
        query = query.where(attributed_at >= start)
    if end:
        query = query.where(attributed_at < end)

    rows = await db.execute(query)
    return [
        {
            "id": r.id,
            "email": r.email,
            "created_at": r.created_at,
            "via_code": r.via_code,
            "order_count": int(r.order_count or 0),
            "total_spent": int(r.total_spent or 0) if reveal_spend else None,
        }
        for r in rows.all()
    ]


async def _build_timeseries(
    account_id: int,
    db: AsyncSession,
    start: datetime | None,
    end: datetime | None,
    date_from: str | None,
    date_to: str | None,
    tz: str | None = None,
) -> list[dict]:
    zone = order_tz(tz)
    today = datetime.now(zone).date()
    if start and end:
        cur = start.date()
        last = (end - timedelta(days=1)).date()
    elif date_from:
        cur = datetime.fromisoformat(date_from).date()
        last = date_to if date_to else today
        if isinstance(last, str):
            last = datetime.fromisoformat(last).date()
    elif date_to:
        last = datetime.fromisoformat(date_to).date()
        cur = last - timedelta(days=29)
    else:
        last = today
        cur = last - timedelta(days=29)

    days: list[dict] = []
    d = cur
    while d <= last:
        days.append({
            "date": d.isoformat(),
            "clicks": 0,
            "signups": 0,
            "orders": 0,
            "revenue": 0,
            "commission": 0,
        })
        d = d + timedelta(days=1)

    if not days:
        return days

    day_index = {datetime.fromisoformat(pt["date"]).date(): pt for pt in days}

    # Bucket by the viewer's calendar day, like `today` and the range, and bound
    # each aggregate to the visible window so we never scan full history.
    win_start = datetime(cur.year, cur.month, cur.day, tzinfo=zone)
    win_end = datetime(last.year, last.month, last.day, tzinfo=zone) + timedelta(days=1)

    # literal_column keeps the zone out of a bind param so the SELECT and GROUP BY
    # expressions render identically (Postgres rejects grouping otherwise). The
    # key comes from ZoneInfo (a real tzdb name), never from raw input.
    zone_sql = literal_column("'" + zone.key.replace("'", "") + "'")

    def _utc_day(col):
        return func.date(func.timezone(zone_sql, col))

    clicks_by_day = await db.execute(
        select(_utc_day(AffiliateClick.created_at), func.count(AffiliateClick.id))
        .where(
            AffiliateClick.affiliate_account_id == account_id,
            AffiliateClick.created_at >= win_start,
            AffiliateClick.created_at < win_end,
        )
        .group_by(_utc_day(AffiliateClick.created_at))
    )
    for d_str, cnt in clicks_by_day.all():
        d = datetime.fromisoformat(str(d_str)).date()
        if d in day_index:
            day_index[d]["clicks"] = int(cnt)

    signups_by_day = await db.execute(
        select(_utc_day(Account.created_at), func.count(Account.id))
        .where(
            Account.referred_by_id == account_id,
            Account.referred_via_promotion_id.is_(None),
            Account.created_at >= win_start,
            Account.created_at < win_end,
        )
        .group_by(_utc_day(Account.created_at))
    )
    for d_str, cnt in signups_by_day.all():
        d = datetime.fromisoformat(str(d_str)).date()
        if d in day_index:
            day_index[d]["signups"] = int(cnt)

    comm_by_day = await db.execute(
        select(
            _utc_day(AffiliateCommission.created_at),
            func.count(AffiliateCommission.id),
            func.coalesce(func.sum(AffiliateCommission.amount), 0),
        )
        .where(
            AffiliateCommission.affiliate_account_id == account_id,
            AffiliateCommission.created_at >= win_start,
            AffiliateCommission.created_at < win_end,
            _PAID_COMMISSION,
        )
        .group_by(_utc_day(AffiliateCommission.created_at))
    )
    for d_str, cnt, amt in comm_by_day.all():
        d = datetime.fromisoformat(str(d_str)).date()
        if d in day_index:
            day_index[d]["orders"] = int(cnt)
            day_index[d]["commission"] = int(amt)

    rev_by_day = await db.execute(
        select(
            _utc_day(AffiliateCommission.created_at),
            func.coalesce(func.sum(Order.total_amount), 0),
        )
        .join(AffiliateCommission, AffiliateCommission.order_id == Order.id)
        .where(
            AffiliateCommission.affiliate_account_id == account_id,
            AffiliateCommission.created_at >= win_start,
            AffiliateCommission.created_at < win_end,
            _PAID_COMMISSION,
        )
        .group_by(_utc_day(AffiliateCommission.created_at))
    )
    for d_str, amt in rev_by_day.all():
        d = datetime.fromisoformat(str(d_str)).date()
        if d in day_index:
            day_index[d]["revenue"] = int(amt)

    return days
