networks:
  market_site_dev:
    name: market_site_dev
    driver: bridge

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/marketplace-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace"]
      interval: 5s
      retries: 5
    networks:
      - market_site_dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - market_site_dev
