from sqlalchemy import CheckConstraint, Computed, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from src.database import Base

# Search corpus (see alembic dx1a2b3c4d5e6): both locale names + slug,
# lower-cased and diacritic-stripped by PostgreSQL.
CATEGORY_SEARCH_TEXT_SQL = (
    "immutable_unaccent(lower("
    "coalesce(name, '') || ' ' || "
    "coalesce(i18n->'vi'->>'name', '') || ' ' || "
    "coalesce(i18n->'en'->>'name', '') || ' ' || "
    "coalesce(slug, '')"
    "))"
)


class Category(Base):
    __tablename__ = "categories"
    __table_args__ = (
        CheckConstraint(
            "commission_rate IS NULL OR (commission_rate >= 0 AND commission_rate <= 100)",
            name="ck_categories_commission_rate_range",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    slug: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    icon: Mapped[str | None] = mapped_column(String(255), nullable=True)
    parent_id: Mapped[int | None] = mapped_column(ForeignKey("categories.id"), nullable=True)
    sort_order: Mapped[int] = mapped_column(Integer, default=0)
    is_active: Mapped[bool] = mapped_column(default=True)
    commission_rate: Mapped[float | None] = mapped_column(Float, nullable=True)
    # { "en": {"name": "..."}, "vi": {"name": "..."} } — scalars remain legacy fallback
    i18n: Mapped[dict] = mapped_column(JSONB, nullable=False, server_default="{}", default=dict)
    # Generated by PostgreSQL; never assigned from Python.
    search_text: Mapped[str] = mapped_column(Text, Computed(CATEGORY_SEARCH_TEXT_SQL, persisted=True), nullable=False)
