import type { AuditItem } from "./types.ts";

/** Subset of Front-End Checklist mapped onto current Proxora surfaces. */
export const AUDIT_ITEMS: AuditItem[] = [
  {
    id: "pub-html-lang",
    surface: "public",
    gate: "semantic",
    severity: "p0",
    title: "html lang khớp locale",
    check: "View source /vi và /en: <html lang> là vi hoặc en.",
    routes: ["/vi", "/en"],
    evidence: "frontend/app/[locale]/layout.tsx — <html lang={locale}>",
    baseline: "pass",
  },
  {
    id: "pub-html-main",
    surface: "public",
    gate: "semantic",
    severity: "p1",
    title: "Đúng một landmark main",
    check: "Accessibility tree trang chủ có một main. Nav/footer không nằm trong main.",
    routes: ["/vi"],
    evidence: "layout.tsx bọc children trong <main>. AdminShell thêm main thứ hai trên /admin.",
    baseline: "pass",
  },
  {
    id: "pub-html-h1",
    surface: "public",
    gate: "semantic",
    severity: "p1",
    title: "Mỗi trang public một H1 rõ việc",
    check: "Home, /categories, /categories/[id], /products/[id] mỗi trang đúng một H1, không nhảy cấp.",
    routes: ["/vi", "/vi/categories", "/vi/products"],
    evidence: "Chưa có test heading. Phải xem DOM thật.",
    baseline: "unknown",
  },
  {
    id: "pub-html-search",
    surface: "public",
    gate: "semantic",
    severity: "p1",
    title: "Ô tìm kiếm type=search và có tên",
    check: "Pills/search ở Market và /categories: input type=search, label hoặc aria-label.",
    routes: ["/vi", "/vi/categories"],
    evidence: "MarketSection search hiện là input thường.",
    baseline: "fail",
  },
  {
    id: "pub-a11y-skip",
    surface: "public",
    gate: "a11y",
    severity: "p1",
    title: "Skip to content",
    check: "Tab lần đầu thấy link bỏ qua nav, nhảy vào main.",
    routes: ["/vi"],
    evidence: "Không có skip link trong layout.",
    baseline: "fail",
  },
  {
    id: "pub-a11y-focus",
    surface: "public",
    gate: "a11y",
    severity: "p0",
    title: "Focus ring nhìn thấy được",
    check: "Tab xuyên TopNav, category card, buy box. Không mất outline.",
    routes: ["/vi", "/vi/products"],
    evidence: "globals.css :focus-visible iris. Một số control tự outline-none.",
    baseline: "unknown",
  },
  {
    id: "pub-a11y-zoom",
    surface: "public",
    gate: "a11y",
    severity: "p0",
    title: "Không khóa pinch-zoom",
    check: "Không có user-scalable=no / maximum-scale=1. Zoom 200% vẫn dùng được.",
    routes: ["/vi"],
    evidence: "Next viewport mặc định. Không thấy khóa zoom.",
    baseline: "pass",
  },
  {
    id: "pub-a11y-motion",
    surface: "public",
    gate: "a11y",
    severity: "p1",
    title: "Tôn trọng reduced motion",
    check: "OS reduce motion: hero/seal/shimmer không chạy.",
    routes: ["/vi"],
    evidence: "globals.css @media (prefers-reduced-motion: reduce)",
    baseline: "pass",
  },
  {
    id: "pub-a11y-cover-alt",
    surface: "public",
    gate: "a11y",
    severity: "p1",
    title: "Cover danh mục/sản phẩm có tên hoặc decorative",
    check: "Ảnh cover: alt mô tả hoặc alt rỗng nếu trùng text bên cạnh.",
    routes: ["/vi", "/vi/categories"],
    evidence: "ProductCover dùng title; cần xem img alt trên DOM.",
    baseline: "unknown",
  },
  {
    id: "pub-a11y-touch",
    surface: "public",
    gate: "a11y",
    severity: "p1",
    title: "Touch target đủ lớn trên mobile",
    check: "375px: pill danh mục, CTA mua, nav icon ≥ 44px hoặc có hit area.",
    routes: ["/vi"],
    evidence: "Chưa đo. Pill cover 16px dễ chạm nhầm.",
    baseline: "unknown",
  },
  {
    id: "pub-perf-lcp",
    surface: "public",
    gate: "perf",
    severity: "p1",
    title: "LCP home / PDP dưới 2.5s mạng thường",
    check: "Performance panel: LCP element là chữ hoặc cover, không phải font ẩn.",
    routes: ["/vi"],
    evidence: "next/font display=swap. Chưa có Lighthouse CI.",
    baseline: "unknown",
  },
  {
    id: "pub-perf-cls",
    surface: "public",
    gate: "perf",
    severity: "p1",
    title: "Cover không đẩy layout",
    check: "Reload home/category: CLS < 0.1. Cover có kích thước trước khi load SVG.",
    routes: ["/vi", "/vi/categories"],
    evidence: "ProductCover là span cố định class h/w, không set width/height trên img.",
    baseline: "unknown",
  },
  {
    id: "pub-seo-title",
    surface: "public",
    gate: "seo",
    severity: "p0",
    title: "Title và description theo từng trang",
    check: "Home, category, PDP mỗi URL một title. PDP chứa tên sản phẩm.",
    routes: ["/vi", "/vi/categories", "/vi/products"],
    evidence: "generateMetadata chỉ ở layout — mọi trang public trùng title.",
    baseline: "fail",
  },
  {
    id: "pub-seo-robots",
    surface: "public",
    gate: "seo",
    severity: "p1",
    title: "robots.txt tồn tại và hợp lệ",
    check: "GET /robots.txt 200, không chặn /, có link sitemap.",
    routes: ["/robots.txt"],
    evidence: "Không có app/robots.ts.",
    baseline: "fail",
  },
  {
    id: "pub-seo-sitemap",
    surface: "public",
    gate: "seo",
    severity: "p1",
    title: "sitemap.xml chỉ trang public",
    check: "/sitemap.xml có home, category, product active. Không có /admin /seller /wallet.",
    routes: ["/sitemap.xml"],
    evidence: "Không có app/sitemap.ts.",
    baseline: "fail",
  },
  {
    id: "pub-seo-og",
    surface: "public",
    gate: "seo",
    severity: "p1",
    title: "Open Graph / Twitter card",
    check: "Share PDP: og:title, og:description, og:image ~1200×630.",
    routes: ["/vi/products"],
    evidence: "Metadata layout không khai báo openGraph/twitter.",
    baseline: "fail",
  },
  {
    id: "pub-seo-favicon",
    surface: "public",
    gate: "seo",
    severity: "p2",
    title: "Favicon hiện trên tab",
    check: "Tab browser có icon, không 404 /favicon.ico.",
    routes: ["/vi"],
    evidence: "Không có app/favicon.ico / icon.png. public/ gần như chỉ covers/.",
    baseline: "fail",
  },
  {
    id: "pub-seo-jsonld",
    surface: "public",
    gate: "seo",
    severity: "p1",
    title: "Product JSON-LD trên PDP",
    check: "View source PDP có schema.org Product + Offer, giá khớp UI.",
    routes: ["/vi/products"],
    evidence: "Chưa thấy JSON-LD.",
    baseline: "fail",
  },
  {
    id: "pub-seo-404",
    surface: "public",
    gate: "seo",
    severity: "p1",
    title: "404 custom, có đường ra",
    check: "/vi/khong-ton-tai ra trang 404 có link về chợ, không stack trắng.",
    routes: ["/vi/khong-ton-tai"],
    evidence: "Không có not-found.tsx.",
    baseline: "fail",
  },
  {
    id: "pub-sec-headers",
    surface: "public",
    gate: "security",
    severity: "p0",
    title: "Security headers còn trên response",
    check: "CSP, nosniff, XFO DENY, Referrer-Policy, Permissions-Policy, COOP. Prod có HSTS.",
    routes: ["/vi"],
    evidence: "frontend/next.config.mjs headers(). CSP còn unsafe-inline.",
    baseline: "pass",
  },
  {
    id: "pub-sec-legal",
    surface: "public",
    gate: "security",
    severity: "p0",
    title: "Footer có Điều khoản và Privacy",
    check: "Mọi trang public: link Terms + Privacy, không 404.",
    routes: ["/vi"],
    evidence: "SiteFooter không thấy terms/privacy.",
    baseline: "fail",
  },
  {
    id: "pub-sec-noopener",
    surface: "public",
    gate: "security",
    severity: "p1",
    title: "Link target=_blank có rel noopener",
    check: "Grep DOM / footer / chat: mọi _blank kèm noopener noreferrer.",
    routes: ["/vi"],
    evidence: "Cần rà trên browser và mã. Chưa khóa bằng test.",
    baseline: "unknown",
  },
  {
    id: "buyer-html-orders",
    surface: "buyer",
    gate: "semantic",
    severity: "p1",
    title: "Danh sách đơn là bảng hoặc list đúng nghĩa",
    check: "Desktop: cột có header. Mobile: mỗi field có nhãn, không chỉ icon.",
    routes: ["/vi/orders"],
    evidence: "orders/page.tsx + OrderCard. Phải xem DOM.",
    baseline: "unknown",
  },
  {
    id: "buyer-a11y-buybox",
    surface: "buyer",
    gate: "a11y",
    severity: "p0",
    title: "Buy box: label, lỗi, keyboard",
    check: "Mua trên PDP: mọi field có label, lỗi đọc được, Enter submit, không kẹt focus.",
    routes: ["/vi/products"],
    evidence: "OrderPanel / DynamicOrderForm. Chưa có axe test.",
    baseline: "unknown",
  },
  {
    id: "buyer-a11y-modal",
    surface: "buyer",
    gate: "a11y",
    severity: "p0",
    title: "Modal đơn / dispute giữ focus",
    check: "Mở DisputeModal: focus vào dialog, Tab không ra ngoài, Esc đóng, trả focus.",
    routes: ["/vi/orders"],
    evidence: "Radix dialog có sẵn pattern; OrderDetailsModal cần xác nhận.",
    baseline: "unknown",
  },
  {
    id: "buyer-a11y-live",
    surface: "buyer",
    gate: "a11y",
    severity: "p1",
    title: "Toast / trạng thái đơn được announce",
    check: "VoiceOver/NVDA: nạp tiền xong, mua xong, lỗi API có live region.",
    routes: ["/vi/orders", "/vi/wallet"],
    evidence: "Chưa thấy aria-live thống nhất.",
    baseline: "unknown",
  },
  {
    id: "buyer-a11y-auth",
    surface: "buyer",
    gate: "a11y",
    severity: "p0",
    title: "Login cho phép paste và password manager",
    check: "Không chặn paste. autocomplete=username/current-password. type=password.",
    routes: ["/vi/login"],
    evidence: "Cần mở form login.",
    baseline: "unknown",
  },
  {
    id: "buyer-perf-orders",
    surface: "buyer",
    gate: "perf",
    severity: "p2",
    title: "Danh sách đơn không đơ khi nhiều bản ghi",
    check: "Tài khoản nhiều đơn: scroll mượt, không render hàng nghìn DOM node.",
    routes: ["/vi/orders"],
    evidence: "Chưa virtualize buyer orders.",
    baseline: "unknown",
  },
  {
    id: "buyer-seo-noindex",
    surface: "buyer",
    gate: "seo",
    severity: "p1",
    title: "orders / wallet / chat không index",
    check: "robots noindex trên /orders /wallet /messages. Không có trong sitemap.",
    routes: ["/vi/orders", "/vi/wallet"],
    evidence: "Chưa thấy robots: noindex trên các route buyer.",
    baseline: "fail",
  },
  {
    id: "buyer-sec-cookie",
    surface: "buyer",
    gate: "security",
    severity: "p0",
    title: "Session chỉ nằm HttpOnly cookie",
    check: "Application tab: dx_session HttpOnly. Không có token trong localStorage.",
    routes: ["/vi/orders"],
    evidence: "BFF app/api/[...path]/route.ts httpOnly. AGENTS cấm token trên client.",
    baseline: "pass",
  },
  {
    id: "seller-html-tables",
    surface: "seller",
    gate: "semantic",
    severity: "p1",
    title: "Products / inventory / orders là data table",
    check: "Desktop có thead. Mobile stack có nhãn field.",
    routes: ["/vi/seller/products", "/vi/seller/inventory", "/vi/seller/orders"],
    evidence: "Workbench đang migrate. Phải xem từng trang.",
    baseline: "unknown",
  },
  {
    id: "seller-a11y-forms",
    surface: "seller",
    gate: "a11y",
    severity: "p0",
    title: "Tạo/sửa sản phẩm: checklist + lỗi đọc được",
    check: "Keyboard hết form. Publish disabled có lý do. Lỗi field không chỉ màu.",
    routes: ["/vi/seller/products/new"],
    evidence: "Form seller còn WIP, setup_status chưa gồm merchandising.",
    baseline: "fail",
  },
  {
    id: "seller-a11y-upload",
    surface: "seller",
    gate: "a11y",
    severity: "p1",
    title: "Upload kho có tiến trình và lỗi từng dòng",
    check: "Chọn file: tên file, số dòng, lỗi đọc được, không mất focus.",
    routes: ["/vi/seller/inventory"],
    evidence: "Bulk upload có skip duplicates. Cần xác nhận a11y.",
    baseline: "unknown",
  },
  {
    id: "seller-perf-inventory",
    surface: "seller",
    gate: "perf",
    severity: "p0",
    title: "Inventory 1000 dòng không đóng tab",
    check: "Kho ~1000 resource: first paint, scroll, filter. Không load hết một cục nếu đơ.",
    routes: ["/vi/seller/inventory"],
    evidence: "Đã từng flag load 1000-row. Chưa virtualize.",
    baseline: "fail",
  },
  {
    id: "seller-seo-noindex",
    surface: "seller",
    gate: "seo",
    severity: "p1",
    title: "Toàn bộ /seller noindex",
    check: "Meta robots noindex trên dashboard seller.",
    routes: ["/vi/seller/products"],
    evidence: "Chưa thấy noindex seller layout.",
    baseline: "fail",
  },
  {
    id: "seller-sec-covers",
    surface: "seller",
    gate: "security",
    severity: "p1",
    title: "Không upload/hotlink ảnh sản phẩm",
    check: "Create/update không gửi images blob. cover_id ngoài allowlist bị 422.",
    routes: ["/vi/seller/products/new"],
    evidence: "Backend reject images, chỉ nhận cover_id. Picker seller chưa có.",
    baseline: "pass",
  },
  {
    id: "admin-html-tables",
    surface: "admin",
    gate: "semantic",
    severity: "p1",
    title: "Bảng admin có header cột",
    check: "Orders, deposits, categories: th hoặc role=columnheader.",
    routes: ["/vi/admin/orders", "/vi/admin/categories"],
    evidence: "Nhiều trang admin còn slate legacy. Phải xem DOM.",
    baseline: "unknown",
  },
  {
    id: "admin-a11y-filters",
    surface: "admin",
    gate: "a11y",
    severity: "p1",
    title: "Filter/search có label",
    check: "Ô lọc orders/products: không phải icon-only vô danh.",
    routes: ["/vi/admin/orders", "/vi/admin/products"],
    evidence: "Nhiều input chỉ có placeholder.",
    baseline: "unknown",
  },
  {
    id: "admin-a11y-nav",
    surface: "admin",
    gate: "a11y",
    severity: "p1",
    title: "Sidebar keyboard + collapsed có tên",
    check: "Tab hết nav. Collapsed: title/aria-label. Mobile menu Esc đóng.",
    routes: ["/vi/admin"],
    evidence: "AdminShell có title khi collapsed, aria-label mở menu.",
    baseline: "pass",
  },
  {
    id: "admin-seo-noindex",
    surface: "admin",
    gate: "seo",
    severity: "p0",
    title: "/admin không index",
    check: "Mọi /admin/* noindex. robots.txt Disallow /admin.",
    routes: ["/vi/admin"],
    evidence: "Không robots.ts. Layout admin không set robots noindex.",
    baseline: "fail",
  },
  {
    id: "admin-sec-gate",
    surface: "admin",
    gate: "security",
    severity: "p0",
    title: "Không admin thì không thấy trang",
    check: "Logout / user thường vào /admin/site-audit → login. Network không lộ data admin.",
    routes: ["/vi/admin/site-audit"],
    evidence: "admin/layout.tsx redirect nếu thiếu role admin.",
    baseline: "pass",
  },
  {
    id: "admin-sec-csp-inline",
    surface: "admin",
    gate: "security",
    severity: "p2",
    title: "Ghi nhận nợ CSP unsafe-inline",
    check: "Không thêm inline script mới. Ghi ticket nếu siết CSP.",
    routes: ["/vi/admin"],
    evidence: "next.config.mjs script-src 'self' 'unsafe-inline'.",
    baseline: "na",
  },
];

export const SURFACE_LABELS: Record<AuditItem["surface"], string> = {
  public: "Public",
  buyer: "Buyer",
  seller: "Seller",
  admin: "Admin",
};

export const GATE_LABELS: Record<AuditItem["gate"], string> = {
  semantic: "HTML / semantic",
  a11y: "Form / a11y",
  perf: "Perf",
  seo: "SEO",
  security: "Security / legal",
};

export const SEVERITY_LABELS: Record<AuditItem["severity"], string> = {
  p0: "P0",
  p1: "P1",
  p2: "P2",
};

export function catalogIntegrity(items: AuditItem[] = AUDIT_ITEMS): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const item of items) {
    if (!item.id || ids.has(item.id)) errors.push(`duplicate or empty id: ${item.id}`);
    ids.add(item.id);
    if (!item.title.trim() || !item.check.trim() || !item.evidence.trim()) {
      errors.push(`${item.id} missing copy`);
    }
    if (item.routes.length === 0) errors.push(`${item.id} has no routes`);
  }
  return errors;
}

export const BASELINE_LABELS: Record<AuditItem["baseline"], string> = {
  pass: "Code gợi ý đạt",
  fail: "Code gợi ý thiếu",
  unknown: "Phải xem browser",
  na: "Nợ đã biết",
};
